stages:
  - pre-flight
  - build
  - test

variables:
  BUILD_DIR: build
  GIT_SUBMODULE_STRATEGY: recursive

# Build stage components

.macos_runner: &macos_runner
  tags:
    - macos
    - m1

.linux_runner: &linux_runner
  tags:
    - linux
    - nvidia-docker

.windows_runner: &windows_runner
  tags:
    - win10-gpu

.linux_dependencies: &linux_dependencies
  before_script:
    - echo Dorado dependency stage
    - apt-get update && apt-get install -y --no-install-recommends libhdf5-dev libssl-dev libzstd-dev

.build_dorado: &build_dorado
  stage: build
  script:
    - echo Dorado build stage
    - cmake ${BUILD_OPTIONS} -S . -B ${BUILD_DIR}
    - cmake --build ${BUILD_DIR} --config Release --target install -j 8
    - ctest -C Release --test-dir ${BUILD_DIR}
  artifacts:
    paths:
      - dist
    expire_in: 1 day

.build_dorado_archive: &build_dorado_archive
  stage: build
  script:
    - cmake ${BUILD_OPTIONS} -S . -B ${BUILD_DIR}
    - cmake --build ${BUILD_DIR} --config Release -j 8
    - cpack --config ${BUILD_DIR}/CPackConfig.cmake
  artifacts:
    paths:
      - archive
    expire_in: 1 day

# Pre-flight stages

pre-commit:
  image: ${DORADO_PRECOMMIT}
  stage: pre-flight
  script:
    - pip install pre-commit
    - pre-commit run --all-files
  <<: *linux_runner

# Build stages

build:linux:x86:focal:install_deps:
  image: ${DORADO_DOCKER_ROOT}/dorado-no-deps-20.04:1.0
  <<: *linux_dependencies
  <<: *linux_runner
  <<: *build_dorado
  when: manual

build:linux:x86:focal:
  image: ${DORADO_DOCKER_ROOT}/dorado-deps-20.04:1.0
  variables:
    BUILD_OPTIONS: "-DDORADO_LIBTORCH_DIR=/usr/local/libtorch -DBUILD_KOI_FROM_SOURCE=ON -DGITLAB_CI_TOKEN=${CI_JOB_TOKEN}"
  <<: *linux_runner
  <<: *build_dorado

build:linux:x86:focal_koi_download:
  image: ${DORADO_DOCKER_ROOT}/dorado-deps-20.04:1.0
  variables:
    BUILD_OPTIONS: "-DDORADO_LIBTORCH_DIR=/usr/local/libtorch"
  <<: *linux_runner
  <<: *build_dorado

build:windows:
  variables:
    BUILD_OPTIONS: "-A x64 -DBUILD_KOI_FROM_SOURCE=ON -DGITLAB_CI_TOKEN=${CI_JOB_TOKEN}"
  <<: *windows_runner
  <<: *build_dorado
  before_script:
    - export PATH=${PATH}:${PWD}/dist/bin

build:windows_koi_download:
  variables:
    BUILD_OPTIONS: "-A x64"
  <<: *windows_runner
  <<: *build_dorado
  before_script:
    - export PATH=${PATH}:${PWD}/dist/bin

build:macos:m1:
  variables:
  <<: *macos_runner
  <<: *build_dorado

build_archive:linux:x86:focal:
  image: ${DORADO_DOCKER_ROOT}/dorado-deps-20.04:1.0
  variables:
    BUILD_OPTIONS: "-DDORADO_LIBTORCH_DIR=/usr/local/libtorch -DBUILD_KOI_FROM_SOURCE=ON -DGITLAB_CI_TOKEN=${CI_JOB_TOKEN}"
  <<: *linux_runner
  <<: *build_dorado_archive
  when: manual

build_archive:linux:x86:centos7:
  image: ${DORADO_DOCKER_ROOT}/dorado-deps-centos7:1.0
  variables:
    BUILD_OPTIONS: "-DDORADO_LIBTORCH_DIR=/usr/local/libtorch -DBUILD_KOI_FROM_SOURCE=ON -DGITLAB_CI_TOKEN=${CI_JOB_TOKEN} -DOPENSSL_ROOT_DIR=/usr/lib64/openssl11/ -DOPENSSL_INCLUDE_DIR=/usr/include/openssl11 -DDORADO_USING_OLD_CPP_ABI=ON -DDYNAMIC_HDF=ON"
  <<: *linux_runner
  <<: *build_dorado_archive
  when: manual

build_archive:windows:
  variables:
    BUILD_OPTIONS: "-A x64 -DBUILD_KOI_FROM_SOURCE=ON -DGITLAB_CI_TOKEN=${CI_JOB_TOKEN}"
  <<: *windows_runner
  <<: *build_dorado_archive
  when: manual

build_archive:macos:m1:
  variables:
  <<: *macos_runner
  <<: *build_dorado_archive
  when: manual

# Test stage components

.test_dorado: &test_dorado
  stage: test
  script:
    - echo Dorado app test stage
    - ./dist/bin/dorado download --model dna_r9.4.1_e8_hac@v3.3
    - ./dist/bin/dorado basecaller dna_r9.4.1_e8_hac@v3.3 ./tests/data/ -r 1 -b 384 > calls.sam
    - ./dist/bin/dorado basecaller dna_r9.4.1_e8_hac@v3.3 ./tests/data/ -r 1 -x cpu > calls.sam

.test_archive: &test_archive
  stage: test
  script:
    - tar -xzf archive/dorado-*.gz
    - ldd ./dorado-*/bin/dorado
    # We just want to check that dorado will run here, so simply call the help command
    - ./dorado-*/bin/dorado --help

# Test stages

test:linux:x86:focal:
  image: ${DORADO_DEPS}
  <<: *linux_runner
  <<: *test_dorado
  needs:
    - build:linux:x86:focal

test:macos:m1:
  <<: *macos_runner
  <<: *test_dorado
  needs:
    - build:macos:m1

# Test that you can run dorado in a clean cuda 20.04 environment
test_archive:linux:x86:20.04_nvidia:
  image: nvidia/cuda:11.3.0-devel-ubuntu20.04
  <<: *linux_runner
  <<: *test_archive
  needs:
    - build_archive:linux:x86:centos7

# Test that you can run dorado in a clean cpu 18.04 environment
test_archive:linux:x86:18.04:
  image: ubuntu:18.04
  <<: *linux_runner
  <<: *test_archive
  needs:
    - build_archive:linux:x86:centos7

# Test that you can run dorado in a clean cpu 20.04 environment
test_archive:linux:x86:20.04:
  image: ubuntu:20.04
  <<: *linux_runner
  <<: *test_archive
  needs:
    - build_archive:linux:x86:centos7

# Single read eval

test:sre-test:
  stage: test
  when: manual
  image: ${TRIGGER_IMAGE}
  dependencies: []
  variables:
    GIT_STRATEGY: none
  script:
    - |
      curl -i --header "Content-Type: application/json" \
      --request POST \
      --data '{
          "key": "'${MLHUB_TRIGGER_KEY}'",
          "job_name": "Dorado SRE: '${CI_COMMIT_REF_NAME}' - '"$CI_COMMIT_TITLE"' ",
          "script_parameters": {
              "git_checkout":"'${CI_COMMIT_SHA}'",
              "branch_name":"'${CI_COMMIT_REF_NAME}'",
              "sre_output":"'${SRE_OUTPUT_ROOT}'/'${CI_COMMIT_SHA}'/",
              "models":["dna_r10.4.1_e8.2_400bps_fast@v4.0.0","dna_r10.4.1_e8.2_400bps_hac@v4.0.0","dna_r10.4.1_e8.2_400bps_sup@v4.0.0"]
          }
      }' \
      ${MLHUB_TRIGGER_URL}
