name: build-dorado

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Clean up diskspace
      run: sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost "$AGENT_TOOLSDIRECTORY"
    - name: Set up cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.25.x'
    - uses: Jimver/cuda-toolkit@v0.2.10
      id: cuda-toolkit
      with:
        cuda: '11.8.0'
    - name: Install dependencies from apt
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libhdf5-dev libssl-dev libzstd-dev autoconf
    - name: Build dorado
      run: |
        cmake -S . -B cmake-build
        cmake --build cmake-build --config Release -j 8
    - name: Test dorado
      run: |
        cmake --build cmake-build --config Release --target install -j 8
        ctest -C Release --test-dir cmake-build --output-on-failure --verbose
